blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include,url
import django.contrib.auth.views

from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout', kwargs={'next_page': '/posts'}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),
    url(r'^posts/',include("posts.urls", namespace = "posts")),
    
]

if settings.DEBUG == True:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import include,url
from . import views



urlpatterns = [
    
    url(r'^$',views.posts_list, name="Home"),
    url(r'^create/$',views.posts_create, name="create"),
    url(r'^about/$',views.about, name="about"),
    url(r'^contact/$',views.contact, name="contact"),
    # url(r'^(?P<slug>.+)$',views.posts_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/$',views.posts_update, name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$',views.posts_delete, name="delete"),
    url(r'^(?P<slug>[\w-]+)$',views.posts_detail, name="detail"),
]
 

posts/models.py
from django.db import models
from django.conf import settings 
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from django.utils.safestring import mark_safe


from markdown_deux import markdown

''' def upload_location(instance,filename):
	return "%s/%s"%instance.id,filename
'''
class PostManager(models.Manager):
	def active(self,*args,**kargs):
		return super(PostManager,self).filter(draft=False).filter(publish__lte=timezone.now())

class Post(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	title = models.CharField(max_length=120)
	description = models.CharField(max_length=200, blank=True)
	slug = models.SlugField(unique = True)
	image = models.FileField(null=True,blank= True) 
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateField(auto_now=False, auto_now_add=False,default = timezone.now().date(),null=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	objects = PostManager()

	def __str__(self):
		return self.title; 

	def get_absolute_url(self):
		return reverse("posts:detail",kwargs={"slug":self.slug})
		# return "/posts/%s/"%(self.id)

	def get_marked_content(self):
		
		return mark_safe(markdown(self.content))

	class Meta:
		ordering = ["-timestamp","-updated"]

def create_slug(instance, new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug=new_slug
	qs = Post.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s"%(slug,qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug

'''For Adding Slug Field'''
def pre_save_post_receiver(signal,instance,*args,**kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)
pre_save.connect(pre_save_post_receiver,sender=Post)


	

posts/forms.py
from pagedown.widgets import PagedownWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit


from django import forms

from .models import Post

class PostForm(forms.ModelForm):

	# define custom validator to check the number of words in content
	content = forms.CharField(widget=PagedownWidget())
	publish = forms.DateField(widget=forms.SelectDateWidget())
	def clean_content(self):
		content = self.cleaned_data['content']

		if len(content.split())<10:
			raise forms.ValidationError("Not Enough Content..")
		return content
	class Meta: 
		model = Post
		
		fields = ('title', 'description','content', 'image','draft','publish')
		labels = {
			'image': ('Preview Image'),
		}
		help_texts = {
			'draft': ('If set Post will remain as draft and will not be visible to public'),
		}
		# error_messages = {
		# 	'name': {
		#     	'max_length': _("This writer's name is too long."),
		# 	},
		# }

posts/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
# Create your views here.
from .models import Post
from .forms import PostForm

def posts_list(request):

	allposts_list = Post.objects.active()
	if  request.user.is_staff or  request.user.is_superuser:
		allposts_list = Post.objects.all()
	# allposts_list = Contacts.objects.all()
	query = request.GET.get("q")
	if query:
		allposts_list = allposts_list.filter(
						Q(title__icontains=query) |
						Q(content__icontains=query)|
						Q(author__first_name__icontains=query)|
						Q(author__first_name__icontains=query)
						).distinct()
	paginator = Paginator(allposts_list, 5) 

	page = request.GET.get('page')
	try:
		page_posts = paginator.page(page)
	except PageNotAnInteger:
	# If page is not an integer, deliver first page.
		page_posts = paginator.page(1)
	except EmptyPage:
	# If page is out of range (e.g. 9999), deliver last page of results.
		page_posts = paginator.page(paginator.num_pages)
	context = {
		"page_posts": page_posts,
		"title": "Home",
		
		}	
	return render(request,"post_list.html",context)

@login_required
def posts_create(request):
	print("hello")
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404 
	form = PostForm(request.POST or None, request.FILES or None )
	if form.is_valid():
		instance = form.save(commit=False)
		instance.author = request.user
		instance.save()
		# message success
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	

	context = {
		"form": form,
	}
	return render(request, "post_create.html", context)


def posts_detail(request,id = None, slug=None):

	instance = get_object_or_404(Post,slug = slug)
	if instance.draft or instance.publish > timezone.now().date():
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404 
	context = {
		"title" :instance.title,
		"instance": instance

	}
	return render(request,"post_detail.html",context) 



@login_required
def posts_update(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404 
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	return render(request, "post_create.html", context)

	
@login_required
def posts_delete(request,slug = None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404 
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request, "Successfully Deleted")
	return redirect("posts:Home")

def about(request):
	return render(request,"about.html")


def contact(request):
	return render(request,"contact.html")

templates/about.html
{% extends "post_detail.html" %}
{% load static %}

{% block content %}
	
	{% block header %}
	 <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
	    <header class="intro-header" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5),rgba(0,0, 0, 0.5)),url(' {% static "images/mypic_three.jpg" %}')">
	        <div class="container">
	            <div class="row">
	                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	                    <div class="page-heading">
	                        <h1>About Me</h1>
	                        <hr class="small">
	                        <span class="subheading">This is what I do.</span>
	                    </div>
	                </div>
	            </div>
	        </div>
	    </header>
	{% endblock header %}
	{% block about %}
	{% endblock about %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>
    {{ form.media }}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block style %}
	<!-- Bootstrap Core CSS -->
	<link rel='stylesheet' href='{% static "css/bootstrap.min.css" %}'/>
	<!-- Custom CSS -->
	<link rel='stylesheet' href='{% static "css/base-home.css" %}'/>
		   <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

	{% endblock style %}

</head>
		<body> 
		<!-- {% include "messages_display.html" %} -->
		{% include "navbar.html" %}
			
				{% block content %}
				{% endblock content %}
		
			 <!-- /.container -->
				
				{% block footer %}
				{% endblock footer %}

		
			<!-- jQuery -->
			<script src="http://code.jquery.com/jquery-latest.min.js"></script>
			 <!-- Bootstrap Core JavaScript -->
			<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
			<!-- Custom JavaScript -->
			<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
			<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
		</body>
</html>

templates/contact.html
{% extends "about.html" %}
{% load static %}

{% block content %}
	
	{% block header %}
	 <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
	    <header class="intro-header" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5),rgba(0,0, 0, 0.5)),url(' {% static "images/mypic_three.jpg" %}')">
	        <div class="container">
	            <div class="row">
	                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	                    <div class="page-heading">
	                        <h1>Contact Me</h1>
	                        <hr class="small">
	                        <span class="subheading">How can I help You?</span>
	                    </div>
	                </div>
	            </div>
	        </div>
	    </header>
	{% endblock header %}
	{% block contactForm %}
		    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
                
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Email Address</label>
                            <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Phone Number</label>
                            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <hr>
	{% endblock contactForm %}
{% endblock content %}

templates/footer.html
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

templates/messages_display.html
{% if messages %}
	<div class="col-sm-6 col-sm-offset-3">
		<div class='message'>
				
			<ul class="messages">
			    {% for message in messages %}
				     <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
				    {% if "html_safe" in message.tags %}
						<div class="alert alert-success" role="alert">{{ message|safe }}</div>

				    {% else %}
				    	<div class="alert alert-success" role="alert">{{ message }}</div>
				     {% endif %}</li>
			    {% endfor %}
			</ul>

		</div>
	</div>
{% endif %}

templates/navbar.html
	
	<!-- Navigation -->
    <nav class="navbar  navbar-fixed-top navbar-custom" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
             <button type="button"  class="navbar-toggle" data-toggle="collapse" 
                data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url "posts:Home" %}">Django Blog</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url "posts:about" %}">About</a>
                    </li>
                    <li>
                        <a href="{% url "posts:contact" %}">Contact</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                        <a href="{% url "posts:create" %}">Create</a>
                        </li>
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                      <li><a><span class="glyphicon glyphicon-user"></span>&nbsp;<small>Hi, {{ user.username }}</small></a></li>
                      <li><a href="{% url "logout" %}"><small>Logout</small></a></li>
                {% else %}
                <ul class="nav navbar-nav navbar-right">
                  
                  <li><a href="{% url "login" %}">Login</a></li>
                  
                </ul>
            {% endif %}
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

templates/popup.html
<!-- Modal -->
<div class="modal fade" id="myModal{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        Are you sure you want to delete {{post.title}}?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <a href="{% url "posts:delete" post.slug %}" class="btn btn-danger"> <span class="glyphicon glyphicon-trash"></span>&nbsp;Delete</a>
      </div>
    </div>
  </div>
</div>

templates/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}{{block.super}}{% endblock head_title %}
{% block content %}

<div class="col-sm-6 col-sm-offset-3">

<form method="POST" action='' enctype="multipart/form-data"> {% csrf_token %}
	{% crispy form %}
	<input type="submit" class='btn btn-default' value="Create Post">
</form>
</div>
{%endblock%}

templates/post_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load social_share %}

{% block style %}
	{{ block.super }}
	<!-- Custom CSS -->
	<link rel='stylesheet' href='{% static "css/post-detail.css" %}'/>
{% endblock style %}

{% block head_title %}
	{{ instance.title }}| {{block.super}}
{% endblock head_title %}

{% block content %}
	{% block header %}
		 <!-- Page Header -->
		
	    <!-- Set your background image for this header on the line below. -->
	    <header class="intro-header background-image" style="background-image:  linear-gradient(rgba(0, 0, 0, 0.5),rgba(0,0, 0, 0.5)),
	    {% if instance.image %}
	        url('{{instance.image.url}}');
	     {% else %}
	     	 url(' {% static "images/footer_lodyas.png" %}');
	     {% endif %}">
	        <div class="container">
	            <div class="row">
	                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	                    <div class="post-heading">
	                        <h1>{{ instance.title }}</h1>
	                        <h2 class="subheading">{{instance.description }}</h2>
	                        <span class="meta">Posted by <a href="#">{% if instance.author.get_full_name%}{{instance.author.get_full_name}}{% endif %}</a> on {{instance.publish}}</span>
		                </div>
	                </div>
	            </div>
	        </div>
	    </header>
	{% endblock header %}
			   <!-- Post Content -->
	{% block article %}
	    <article>
	        <div class="container">
	            <div class="row">
	                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 marked-content">
					
							{{instance.get_marked_content}}<br/>
							<!-- <a href="{% url "posts:Home" %}">Back</a> -->

					</div>
				</div>
			</div>
		</article>
		<!-- <div class='col-sm-6 col-sm-offset-3'>
		{% post_to_facebook instance.get_absolute_url "Post to Facebook!" %}
		{% post_to_gplus  instance "Post to Google+!" %}
		{% post_to_twitter "New Post: {{instance.title}}. Check it out!" object_or_url "Post to Twitter" %}
		</div> -->
	{% endblock article %}
		

{% endblock content %}
	



     {% block footer %}
        {% include "footer.html" %}
     {% endblock footer %}
	
	     {% block backtotop %}
	    <!-- <div class="top">
	     <a href="#"><i class="fa fa-chevron-circle-up" aria-hidden="true"></i></a>
	     </div> -->
	     {% include "backtop.html" %}
	 {% endblock backtotop%}

templates/post_list.html
	{% extends "base.html" %}
    {% load markdown_deux_tags %}


    {% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}

            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </ul>
    {% endif %}

{% if not page_posts %}
<h3>Sorry! There are no Posts yet....</h3>
{% else %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            {% for post in page_posts %}

            <div class="row">
                <div class="col-sm-6">
                    <div class="post-preview">

                        <a href="{{post.get_absolute_url}}"><h2 class="post-title">{{post.title}}</h2></a>
                        <p class="post-meta"> by <a href="#">  {{post.author.get_full_name}}</a> </p>
                        <p class="post-meta"><span class="glyphicon glyphicon-calendar"></span> Posted on {{ post.publish}}&nbsp;{% if user.is_authenticated and post.draft %}

                            <span class="fa fa-check-circle-o fa-fw" aria-hidden="true">&nbsp;Draft</span>
                            {% endif %}
                        </p>
                    </div>
                </div>
                {% if user.is_authenticated %}

                <div class="col-sm-4 col-sm-offset-2 post-options">

                   <a class="btn btn-danger btn-sm" href="#" data-toggle="modal" data-target="#myModal{{post.id}}"> <span class="glyphicon glyphicon-trash"></span>&nbsp;Delete</a>
                   {% include "popup.html" %}

                   <a href="{% url "posts:update" post.slug %}" type="button" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-pencil"></span>&nbsp;Edit</a> 
               </div>
               {% endif %}
           </div>

           <hr>

           {% if post.image %}
           <img src="{{ post.image.url}}" class="img-responsive" class="img-rounded"/>
           <hr>
           {% endif %}

           <div class="marked-content">
               <p >{{ post.get_marked_content|truncatechars_html:150}}</p> 
           </div>

           <a class="btn btn-default" href="{{post.get_absolute_url}}" >Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

           <hr> 
           {% endfor %} 
       </div>

       <!-- Blog Sidebar Widgets Column -->
       <div class="col-md-4">

        <!-- Blog Search Well -->
        <div class="well">
            <h4>Blog Search</h4>
            <form action="" method="GET">
                <div class="input-group">

                    <input type="text" class="form-control" placeholder="Search Blog"  name="q" value={{request.GET.q}}>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit" id ="search-btn" type="button">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>

                </div>
            </form>
            <!-- /.input-group -->
        </div>

        <!-- Blog Categories Well -->
        <div class="well">
            <h4>Blog Categories</h4>
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-unstyled">
                        <li><a href="#">Category Name</a>
                        </li>
                        <li><a href="#">Category Name</a>
                        </li>
                        <li><a href="#">Category Name</a>
                        </li>
                        <li><a href="#">Category Name</a>
                        </li>
                    </ul>
                </div>
                <!-- /.col-lg-6 -->
                <div class="col-lg-6">
                    <ul class="list-unstyled">
                        <li><a href="#">Category Name</a>
                        </li>
                        <li><a href="#">Category Name</a>
                        </li>
                        <li><a href="#">Category Name</a>
                        </li>
                        <li><a href="#">Category Name</a>
                        </li>
                    </ul>
                </div>
                <!-- /.col-lg-6 -->
            </div>
            <!-- /.row -->
        </div>

        <!-- Side Widget Well -->
        <div class="well">
            <h4>Side Widget Well</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
        </div>

    </div>
</div>
<div>
  <ul class="pagination pagination-lg">
    <li>

      {% if page_posts.has_previous %}
      <a href="?page={{ page_posts.previous_page_number }}" aria-label="Previous">

        <span aria-hidden="true">&laquo;</span>
    </a>
    {% endif %}
</li>

{% for i in page_posts.paginator.page_range %}
<li><a href="?page={{i}}">{{ i }}</a></li>
{% endfor %}

<li>

    {% if page_posts.has_next %}
    <a href="?page={{ page_posts.next_page_number }}" aria-label="Next">
     <span aria-hidden="true">&raquo;</span>
 </a>
 {% endif %}

</li>
</ul>

</div>

</div>

{% endif %}   
{% endblock content %}
{% block footer %}
{% include "footer.html" %}
{% endblock footer %}